class DiagnosticTOFBoard:
    def __init__(self):
        self.time = list()
        self.cmd_error = list()
        self.tof_cfd_vm = list()
        self.tof_pre_tm = list()
        self.tof_reg_tm = list()
        self.tof_mcp_cm = list()
        self.tof_mcp_vm = list()
        self.tof_cm = list()
        self.tof_p5_vm = list()
        self.tof_p6_vm = list()
        self.an_a_thr_reg = list()
        self.an_b0_thr_reg = list()
        self.an_b3_thr_reg = list()
        self.an_c_thr_reg = list()
        self.tof_bd_ctrl_reg = list()
        self.stim_ctrl_reg = list()
        self.stim_cnfg_reg = list()
        self.an_tof3_thr_reg = list()
        self.an_tof2_thr_reg = list()
        self.an_tof1_thr_reg = list()
        self.an_tof0_thr_reg = list()
        self.spare_reg = list()
        self.spare = list()
