class PivotPlatformData:
    def __init__(self):
        self.time = list()
        self.coarse_pot_pri = list()
        self.fine_pot_pri = list()
        self.coarse_pot_red = list()
        self.fine_pot_red = list()
        self.actuator_temp = list()
        self.pcc_board_temp = list()
        self.motor_current_pri = list()
        self.motor_current_red = list()
        self.cumulative_cnt_pri = list()
        self.cumulative_cnt_sgn_pri = list()
        self.cumulative_cnt_red = list()
        self.cumulative_cnt_sgn_red = list()
        self.current_step_cnt_pri = list()
        self.current_step_cnt_red = list()
        self.current_setpt_pri = list()
        self.current_setpt_red = list()
        self.status = list()
        self.spare = list()
