class RawCounts:
    def __init__(self):
        self.time = list()
        self.met_sub = list()
        self.start_a = list()
        self.start_c = list()
        self.stop_b0 = list()
        self.stop_b3 = list()
        self.tof0 = list()
        self.tof1 = list()
        self.tof2 = list()
        self.tof3 = list()
        self.accum_ms = list()
        self.tof0_tof1 = list()
        self.tof0_tof2 = list()
        self.tof1_tof2 = list()
        self.silver_triple = list()
        self.disc_tof0 = list()
        self.disc_tof1 = list()
        self.disc_tof2 = list()
        self.disc_tof3 = list()
