class StaticHousekeeping:
    def __init__(self):
        self.time = list()
        self.cdh_jumper_reg = list()
        self.instr_id = list()
        self.cdh_fpga_version = list()
        self.ifb_fpga_version = list()
        self.bulk_hvps_version = list()
        self.fsw_version = list()
        self.table_version = list()
        self.selected_code_image = list()
        self.selected_table_image = list()
        self.boot_counter = list()
        self.hv_limit = list()
        self.hv_disable = list()
        self.fsw_ver_str = list()
        self.eng_lut_ver_str = list()
        self.sci_lut_ver_str = list()
        self.time_tag_res = list()
